### ISSUE TITLE
Evaluar api Flickr

### ISSUE THREAD

**Issue by JavierVaronBueno** [AndresRey3738/Uni-Manager#12]
Se requiere evaluar cual API para python se adapta mas a nuestras necesidades, ya que Flickr no ofrece una API propia la comunidad ofrece algunas alternativas:

Link: https://www.flickr.com/services/api/

**Comment by DaemonJavox** [comment]
fix #12

se escoge flickrapi compatible con python, el cual nos permitira conectarnos con flickr

**Comment by JavierVaronBueno** [comment]
'fix #12'
Se escoge el api flickrapy 2.3 para python
