### ISSUE TITLE
Busqueda de software analizador de codigo en relacion al lenguaje de programación.

### ISSUE THREAD

**Issue by JavierVaronBueno** [AndresRey3738/Uni-Manager#6]
Se require buscar software para el analisis de codigo python, que permita depurara el proyecto, de tal forma que optimice y mejore las practicas de programación.

**Comment by DaemonJavox** [comment]
El software que se usara para el analisis y depuración de codigo pylint https://www.pylint.org/

**Comment by JavierVaronBueno** [comment]
El software que se usara para el analisis y depuración de codigo pylint https://www.pylint.org/
